Add Jewish calendar
pinkywafer/Anniversaries pull request #87
Opened 2021-01-12 20:24 UTC by chaimt

Add support to add jewish birthdays

2021-01-13 19:38 UTC, pinkywafer commented
Thanks for this!
I'll have to take a while to review this as I have no experience of the hebrew calendar!
Can you please also update the info and readme docs.

2021-01-15 08:02 UTC, chaimt commented
updated documention

2021-02-04 20:09 UTC, pinkywafer commented
ok, @chaimt a few points to go over:
* I'm unsure whether the calendar should be defined and return `Jewish` or `Hebrew`? Either way, I think I'd rather have continuity - At the moment, it is configured as `jewish`, the `calendar_type` attribute returns `jewish`, but the date is listed as `hebrew_date` rather than `jewish_date`.  Could these ALL be either `hebrew` or `jewish` please.
* since the `hebrew_date` attribute is only populated when configured as jewish calendar type, please only return it if configured.
* id_prefix should not be returned as an attribute - it is only used to configure the entity name
* There should not be `@property` methods for attributes, please remove the extra ones for calendar_type and hebrew_date
* templates do not work - in the `async_update` function, `validate_date` must have the calendar type passed to it to prevent it breaking, otherwise it assumes a gregorian date which fails for hebrew dates.
* you have (accidentally I assume!) removed the `icon_soon` line from the readme, please reinstate this
* please also update info.md
* Can you add to the config flow for configuration?
* Currently, any entities configured in config flow do not save the calendar_type, so that needs to be handled by the sensor, even if configuration is added for config_flow as pre-existing entities will not have this saved.

2021-02-12 17:34 UTC, pinkywafer requested changes
Please see the comments on the files
I think a rebase will also be needed as there have been changes to the repo since this PR was opened

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/sensor.py
> +            res[ATTR_HEBREW_DATE] = ""
Only return hebrew dates etc if configured:
```suggestion
        if self._calendar_type == HEBREW_CALENDAR:
            res[ATTR_CALENDAR_TYPE] = self._calendar_type
            res[ATTR_HEBREW_DATE] = "{year}-{month}-{day}".format(year=self._h_date.year,month=self._h_date.month,day=self._h_date.day)

```

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/sensor.py
> +                self._date, self._unknown_year = validate_date(template_date, "")
```suggestion
                self._date, self._unknown_year = validate_date(template_date, self._calendar_type)

```

2021-02-12 17:34 UTC, pinkywafer commented on info.md
> +* calendar_type: Type of calendar to use for entry (gregorian, hebrew) **Default**: gregorian
```suggestion
* calendar_type: returns hebrew if configured using hebrew calendar
```

2021-02-12 17:34 UTC, pinkywafer commented on info.md
> +* hebrew_date: Will display original hebrew data configured
```suggestion
* hebrew_date: Will display original hebrew date if configured using hebrew date
```

2021-02-12 17:34 UTC, pinkywafer commented on README.md
> +
this configuration option has no effect
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on README.md
> +
remove extra blank lines
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/const.py
> +CONF_HEBREW_DATE = "hebrew_date"
unneeded
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/const.py
> +        vol.Optional(CONF_HEBREW_DATE, default=""): cv.string,
unneeded
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/const.py
> +
remove blank lines
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/sensor.py
> +
this is not used as far as I can see
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on custom_components/anniversaries/sensor.py
> +
these are never used
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on info.md
> +| `hebrew_date` | Yes | will display original hebrew data configured
config not used
```suggestion
```

2021-02-12 17:34 UTC, pinkywafer commented on README.md
> +* calendar_type: type of calendar
```suggestion
* calendar_type: hebrew if configured using hebrew calendar

```

2021-02-12 17:34 UTC, pinkywafer commented on README.md
> +| `calendar_type` | Yes | Type of calendar to use for entry (gregorian, hebrew) **Default**: gregorian
currently the hebrew date is only available in yaml mode config, so:
```suggestion
| `calendar_type` | Yes | Type of calendar to use for entry (gregorian, hebrew) **Default**: gregorian _(Note this is ONLY available in YAML configuration)_
```

2024-10-14 13:00 UTC, closed without merging